name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master   # ✅ your repo uses master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # ✅ Install .NET 10 RC manually
      - name: Setup .NET 10 RC
        run: |
          curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 10.0 --quality preview --install-dir $HOME/.dotnet
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV

      # Verify installed version
      - name: Verify .NET Version
        run: dotnet --version

      # ✅ Restore, Build & Publish Blazor WASM
      - name: Restore Dependencies
        run: dotnet restore app/BlazorApp28/BlazorApp28.csproj

      - name: Build Blazor WebAssembly
        run: dotnet build app/BlazorApp28/BlazorApp28.csproj --configuration Release --no-restore

      - name: Publish Blazor WebAssembly
        run: dotnet publish app/BlazorApp28/BlazorApp28.csproj -c Release -o app/build

      # ✅ Deploy prebuilt output to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FOREST_0906A4B10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "app/build/wwwroot" # Published WASM output
          api_location: "Api"               # Optional: Azure Functions
          output_location: ""               # Empty because we already published

  # ✅ Handle PR closures
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FOREST_0906A4B10 }}
          action: "close"
